# .bashrc

export _BASHRC=1

# Global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

if [ -z "$_BASH_PROFILE" ]; then
    . ~/.bash_profile
fi

unset _BASH_PROFILE

umask 002

export HISTSIZE=99999
export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
shopt -s globstar

if [ "$TERM" != "screen" ];
then
    export TERM=xterm
fi
export SVN_EDITOR=nano


export WUVT_PLATFORM="DEV"
export USER=$(/usr/bin/whoami)
export LOGNAME=$(/usr/bin/whoami)


export WUVT_ROOT=/home/$USER/wuvt/

export HOSTNAME=`hostname`
export HOST=$HOSTNAME


# PATH
PATH=$PATH:$WUVT_ROOT/bin:/usr/local/bin:$WUVT_ROOT/tools:/usr/local/pgsql/bin:/sbin:/usr/sbin


# Python
export PYTHONSTARTUP=~/.pythonrc.py
export PYTHONOPTS="-u"
export PYTHONPATH=$WUVT_ROOT/lib:$WUVT_ROOT/bin:$WUVT_ROOT/tools:/usr/local/pgsql/bin:/usr/local/pgsql/lib:$HOME/wuvt


# Django
export DJANGO_SETTINGS_MODULE=wuvt.settings


# Aliases

alias sortImports="PYTHONPATH=$PYTHONPATH:. sortImports"
alias pylint="\pylint --generated-members=objects $* 2>/dev/null"

alias ls='ls --color=auto'
alias log='cd $HOME/wuvt/log'
alias rlog='for file in $HOME/wuvt/log/*.log; do > $file; done'
alias vlog='less $HOME/wuvt/log/wuvt.log'
alias tlog='less +F $HOME/wuvt/log/wuvt.log'
alias clog='cat $HOME/wuvt/log/wuvt.log'
alias config='cd $HOME/wuvt/config'

alias myps='ps auxww | grep "^$USER" | grep -v grep'
alias myps2='ps auxww | grep "^$USER" | grep -v grep | grep -v xterm | grep -v sshd | grep -v bash | grep -v ps | grep -v dbus | grep -vi " SCREEN"'



