#!/usr/bin/python

import subprocess
import sys
import os
import time

if len(sys.argv) < 2:
    print "Usage: " + sys.argv[0] + " [filename]"
    sys.exit(1)

subprocess.Popen("pep8formatter.py " + ' '.join(sys.argv[1:]), shell=True).wait()
subprocess.Popen("stripWhitespace.py " + ' '.join(sys.argv[1:]), shell=True).wait()

# sortImports must have pwd=directory of python file for proper imports, so ensure that is the case
dirFilePairs = {}
for fileName in sys.argv[1:]:
    directory = os.path.abspath(os.path.dirname(fileName))
    dirFilePairs[directory] = dirFilePairs.setdefault(directory, []) + [os.path.basename(fileName), ]

# Launch a subprocess in each directory
pipes = []

for directory, files in dirFilePairs.iteritems():
    pipes.append( subprocess.Popen('PYTHONPATH=$PYTHONPATH:. sortImports ' + ' '.join(files), shell=True, cwd=directory) )


while len(pipes):
    pipesToKeep = []
    for i in range(len(pipes)):
        if pipes[i].poll() == None:
            pipesToKeep.append(pipes[i])
    pipes = pipesToKeep
    time.sleep(1)

